version: "2"         # required to adjust maintainability checks

exclude_patterns:
- "backend/tmp"
- "backend/sqlc"
- "backend/graph/**/generated/generated.go"
- "backend/graph/**/model/models_gen.go"
- "cms/src/hooks/sync-to-legacy"
- "web/**/*generated*.ts"
- "**/*.d.ts"

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 10
