version: '3'
services:
  pubsub:
    ports:
      - "8681:8681"
    image: thekevjames/gcloud-pubsub-emulator:latest
  db:
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:13
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432/tcp"
    environment:
    - POSTGRES_USER=${PGUSER}
    - POSTGRES_PASSWORD=${PGPASSWORD}
    - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    ports:
    - "6378:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=bccm123
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:8080"
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization

volumes:
  db-data:
    driver: local
