version: '3'
services:
  pubsub:
    ports:
      - "8681:8681"
    image: thekevjames/gcloud-pubsub-emulator:latest
  db:
    image: postgres:13
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432/tcp
    environment:
    - POSTGRES_USER=btv
    - POSTGRES_PASSWORD=btv123

volumes:
  db-data:
    driver: local

