version: '3'
services:
  pubsub:
    ports:
      - "8681:8681"
    image: thekevjames/gcloud-pubsub-emulator:latest
  db:
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:13
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432/tcp"
    environment:
    - POSTGRES_USER=${PGUSER}
    - POSTGRES_PASSWORD=${PGPASSWORD}
    - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    ports:
    - "6378:6379"

volumes:
  db-data:
    driver: local

