minimumReleaseAge: 1440
allowBuilds:
  '@parcel/watcher': true
  browser-tabs-lock: true
  esbuild: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - vue-demi
minimumReleaseAgeExclude:
  - '@nuxt/icon@2.2.5'
  - '@tailwindcss/node@4.3.2'
  - '@tailwindcss/oxide-android-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-x64@4.3.2'
  - '@tailwindcss/oxide-freebsd-x64@4.3.2'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.2'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.2'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.2'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.2'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.2'
  - '@tailwindcss/oxide@4.3.2'
  - '@tailwindcss/vite@4.3.2'
  - prettier@3.9.4
  - tailwindcss@4.3.2
