# Start by building the application.
FROM golang:1.18-alpine as build

WORKDIR /go/src
ADD go.mod /go/src/go.mod
ADD go.sum /go/src/go.sum
RUN go get -d -v ./...

ADD ./backend /go/src/backend
RUN CGO_ENABLED=0 go build -o /app ./backend/cmd/jobs

FROM gcr.io/distroless/static
COPY --from=build /app /app
CMD ["/app"]
