-- +goose Up

ALTER DEFAULT PRIVILEGES FOR USER builder IN SCHEMA public GRANT SELECT ON SEQUENCES TO onsite_backup;
ALTER DEFAULT PRIVILEGES FOR USER builder IN SCHEMA public GRANT SELECT ON TABLES TO onsite_backup;

ALTER DEFAULT PRIVILEGES FOR USER builder IN SCHEMA stats GRANT SELECT ON SEQUENCES TO onsite_backup;
ALTER DEFAULT PRIVILEGES FOR USER builder IN SCHEMA stats GRANT SELECT ON TABLES TO onsite_backup;

ALTER DEFAULT PRIVILEGES FOR USER builder IN SCHEMA users GRANT SELECT ON SEQUENCES TO onsite_backup;
ALTER DEFAULT PRIVILEGES FOR USER builder IN SCHEMA users GRANT SELECT ON TABLES TO onsite_backup;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO onsite_backup;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO onsite_backup;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO onsite_backup;

-- +goose Down

--- NOOP
