// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
	null_v4 "gopkg.in/guregu/null.v4"
)

type Ageratings struct {
	Code        string         `db:"code" json:"code"`
	Sort        null_v4.Int    `db:"sort" json:"sort"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	DateUpdated sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Title       null_v4.String `db:"title" json:"title"`
}

type AgeratingsTranslations struct {
	ID             int32          `db:"id" json:"id"`
	AgeratingsCode null_v4.String `db:"ageratings_code" json:"ageratingsCode"`
	LanguagesCode  null_v4.String `db:"languages_code" json:"languagesCode"`
	Title          null_v4.String `db:"title" json:"title"`
}

type Assetfiles struct {
	ID          int32          `db:"id" json:"id"`
	UserCreated uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Filename    null_v4.String `db:"filename" json:"filename"`
	Type        null_v4.String `db:"type" json:"type"`
	Storage     null_v4.String `db:"storage" json:"storage"`
	AssetID     null_v4.Int    `db:"asset_id" json:"assetID"`
}

type Assets struct {
	ID          int32          `db:"id" json:"id"`
	UserCreated uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Name        null_v4.String `db:"name" json:"name"`
}

type Calendarevent struct {
	ID          int32          `db:"id" json:"id"`
	Status      string         `db:"status" json:"status"`
	UserCreated uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Start       time.Time      `db:"start" json:"start"`
	End         null_v4.Time   `db:"end" json:"end"`
	Title       null_v4.String `db:"title" json:"title"`
}

type Categories struct {
	ID             int32          `db:"id" json:"id"`
	Sort           null_v4.Int    `db:"sort" json:"sort"`
	UserCreated    uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated    sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated    uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated    sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	AppearInSearch sql.NullBool   `db:"appear_in_search" json:"appearInSearch"`
	Title          null_v4.String `db:"title" json:"title"`
	ParentID       null_v4.Int    `db:"parent_id" json:"parentID"`
}

type CategoriesEpisodes struct {
	ID           int32       `db:"id" json:"id"`
	CategoriesID null_v4.Int `db:"categories_id" json:"categoriesID"`
	EpisodesID   null_v4.Int `db:"episodes_id" json:"episodesID"`
}

type Collections struct {
	ID                   int32          `db:"id" json:"id"`
	Sort                 null_v4.Int    `db:"sort" json:"sort"`
	UserCreated          uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated          sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated          uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated          sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Title                null_v4.String `db:"title" json:"title"`
	Content              null_v4.String `db:"content" json:"content"`
	LegacyOrderBy        null_v4.String `db:"legacy_order_by" json:"legacyOrderBy"`
	ShowEpisodesInSlider sql.NullBool   `db:"show_episodes_in_slider" json:"showEpisodesInSlider"`
	ShowID               null_v4.Int    `db:"show_id" json:"showID"`
	CategoryID           null_v4.Int    `db:"category_id" json:"categoryID"`
}

type DirectusActivity struct {
	ID         int32          `db:"id" json:"id"`
	Action     string         `db:"action" json:"action"`
	User       uuid.NullUUID  `db:"user" json:"user"`
	Timestamp  time.Time      `db:"timestamp" json:"timestamp"`
	Ip         string         `db:"ip" json:"ip"`
	UserAgent  null_v4.String `db:"user_agent" json:"userAgent"`
	Collection string         `db:"collection" json:"collection"`
	Item       string         `db:"item" json:"item"`
	Comment    null_v4.String `db:"comment" json:"comment"`
}

type DirectusCollections struct {
	Collection            string                `db:"collection" json:"collection"`
	Icon                  null_v4.String        `db:"icon" json:"icon"`
	Note                  null_v4.String        `db:"note" json:"note"`
	DisplayTemplate       null_v4.String        `db:"display_template" json:"displayTemplate"`
	Hidden                bool                  `db:"hidden" json:"hidden"`
	Singleton             bool                  `db:"singleton" json:"singleton"`
	Translations          pqtype.NullRawMessage `db:"translations" json:"translations"`
	ArchiveField          null_v4.String        `db:"archive_field" json:"archiveField"`
	ArchiveAppFilter      bool                  `db:"archive_app_filter" json:"archiveAppFilter"`
	ArchiveValue          null_v4.String        `db:"archive_value" json:"archiveValue"`
	UnarchiveValue        null_v4.String        `db:"unarchive_value" json:"unarchiveValue"`
	SortField             null_v4.String        `db:"sort_field" json:"sortField"`
	Accountability        null_v4.String        `db:"accountability" json:"accountability"`
	Color                 null_v4.String        `db:"color" json:"color"`
	ItemDuplicationFields pqtype.NullRawMessage `db:"item_duplication_fields" json:"itemDuplicationFields"`
	Sort                  null_v4.Int           `db:"sort" json:"sort"`
	Group                 null_v4.String        `db:"group" json:"group"`
	Collapse              string                `db:"collapse" json:"collapse"`
}

type DirectusDashboards struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Icon        string         `db:"icon" json:"icon"`
	Note        null_v4.String `db:"note" json:"note"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserCreated uuid.NullUUID  `db:"user_created" json:"userCreated"`
}

type DirectusFields struct {
	ID                int32                 `db:"id" json:"id"`
	Collection        string                `db:"collection" json:"collection"`
	Field             string                `db:"field" json:"field"`
	Special           null_v4.String        `db:"special" json:"special"`
	Interface         null_v4.String        `db:"interface" json:"interface"`
	Options           pqtype.NullRawMessage `db:"options" json:"options"`
	Display           null_v4.String        `db:"display" json:"display"`
	DisplayOptions    pqtype.NullRawMessage `db:"display_options" json:"displayOptions"`
	Readonly          bool                  `db:"readonly" json:"readonly"`
	Hidden            bool                  `db:"hidden" json:"hidden"`
	Sort              null_v4.Int           `db:"sort" json:"sort"`
	Width             null_v4.String        `db:"width" json:"width"`
	Translations      pqtype.NullRawMessage `db:"translations" json:"translations"`
	Note              null_v4.String        `db:"note" json:"note"`
	Conditions        pqtype.NullRawMessage `db:"conditions" json:"conditions"`
	Required          sql.NullBool          `db:"required" json:"required"`
	Group             null_v4.String        `db:"group" json:"group"`
	Validation        pqtype.NullRawMessage `db:"validation" json:"validation"`
	ValidationMessage null_v4.String        `db:"validation_message" json:"validationMessage"`
}

type DirectusFiles struct {
	ID               uuid.UUID             `db:"id" json:"id"`
	Storage          string                `db:"storage" json:"storage"`
	FilenameDisk     null_v4.String        `db:"filename_disk" json:"filenameDisk"`
	FilenameDownload string                `db:"filename_download" json:"filenameDownload"`
	Title            null_v4.String        `db:"title" json:"title"`
	Type             null_v4.String        `db:"type" json:"type"`
	Folder           uuid.NullUUID         `db:"folder" json:"folder"`
	UploadedBy       uuid.NullUUID         `db:"uploaded_by" json:"uploadedBy"`
	UploadedOn       time.Time             `db:"uploaded_on" json:"uploadedOn"`
	ModifiedBy       uuid.NullUUID         `db:"modified_by" json:"modifiedBy"`
	ModifiedOn       time.Time             `db:"modified_on" json:"modifiedOn"`
	Charset          null_v4.String        `db:"charset" json:"charset"`
	Filesize         null_v4.Int           `db:"filesize" json:"filesize"`
	Width            null_v4.Int           `db:"width" json:"width"`
	Height           null_v4.Int           `db:"height" json:"height"`
	Duration         null_v4.Int           `db:"duration" json:"duration"`
	Embed            null_v4.String        `db:"embed" json:"embed"`
	Description      null_v4.String        `db:"description" json:"description"`
	Location         null_v4.String        `db:"location" json:"location"`
	Tags             null_v4.String        `db:"tags" json:"tags"`
	Metadata         pqtype.NullRawMessage `db:"metadata" json:"metadata"`
}

type DirectusFolders struct {
	ID     uuid.UUID     `db:"id" json:"id"`
	Name   string        `db:"name" json:"name"`
	Parent uuid.NullUUID `db:"parent" json:"parent"`
}

type DirectusMigrations struct {
	Version   string       `db:"version" json:"version"`
	Name      string       `db:"name" json:"name"`
	Timestamp sql.NullTime `db:"timestamp" json:"timestamp"`
}

type DirectusNotifications struct {
	ID         int32          `db:"id" json:"id"`
	Timestamp  time.Time      `db:"timestamp" json:"timestamp"`
	Status     null_v4.String `db:"status" json:"status"`
	Recipient  uuid.UUID      `db:"recipient" json:"recipient"`
	Sender     uuid.UUID      `db:"sender" json:"sender"`
	Subject    string         `db:"subject" json:"subject"`
	Message    null_v4.String `db:"message" json:"message"`
	Collection null_v4.String `db:"collection" json:"collection"`
	Item       null_v4.String `db:"item" json:"item"`
}

type DirectusPanels struct {
	ID          uuid.UUID             `db:"id" json:"id"`
	Dashboard   uuid.UUID             `db:"dashboard" json:"dashboard"`
	Name        null_v4.String        `db:"name" json:"name"`
	Icon        null_v4.String        `db:"icon" json:"icon"`
	Color       null_v4.String        `db:"color" json:"color"`
	ShowHeader  bool                  `db:"show_header" json:"showHeader"`
	Note        null_v4.String        `db:"note" json:"note"`
	Type        string                `db:"type" json:"type"`
	PositionX   int32                 `db:"position_x" json:"positionX"`
	PositionY   int32                 `db:"position_y" json:"positionY"`
	Width       int32                 `db:"width" json:"width"`
	Height      int32                 `db:"height" json:"height"`
	Options     pqtype.NullRawMessage `db:"options" json:"options"`
	DateCreated sql.NullTime          `db:"date_created" json:"dateCreated"`
	UserCreated uuid.NullUUID         `db:"user_created" json:"userCreated"`
}

type DirectusPermissions struct {
	ID          int32                 `db:"id" json:"id"`
	Role        uuid.NullUUID         `db:"role" json:"role"`
	Collection  string                `db:"collection" json:"collection"`
	Action      string                `db:"action" json:"action"`
	Permissions pqtype.NullRawMessage `db:"permissions" json:"permissions"`
	Validation  pqtype.NullRawMessage `db:"validation" json:"validation"`
	Presets     pqtype.NullRawMessage `db:"presets" json:"presets"`
	Fields      null_v4.String        `db:"fields" json:"fields"`
}

type DirectusPresets struct {
	ID              int32                 `db:"id" json:"id"`
	Bookmark        null_v4.String        `db:"bookmark" json:"bookmark"`
	User            uuid.NullUUID         `db:"user" json:"user"`
	Role            uuid.NullUUID         `db:"role" json:"role"`
	Collection      null_v4.String        `db:"collection" json:"collection"`
	Search          null_v4.String        `db:"search" json:"search"`
	Layout          null_v4.String        `db:"layout" json:"layout"`
	LayoutQuery     pqtype.NullRawMessage `db:"layout_query" json:"layoutQuery"`
	LayoutOptions   pqtype.NullRawMessage `db:"layout_options" json:"layoutOptions"`
	RefreshInterval null_v4.Int           `db:"refresh_interval" json:"refreshInterval"`
	Filter          pqtype.NullRawMessage `db:"filter" json:"filter"`
	Icon            string                `db:"icon" json:"icon"`
	Color           null_v4.String        `db:"color" json:"color"`
}

type DirectusRelations struct {
	ID                    int32          `db:"id" json:"id"`
	ManyCollection        string         `db:"many_collection" json:"manyCollection"`
	ManyField             string         `db:"many_field" json:"manyField"`
	OneCollection         null_v4.String `db:"one_collection" json:"oneCollection"`
	OneField              null_v4.String `db:"one_field" json:"oneField"`
	OneCollectionField    null_v4.String `db:"one_collection_field" json:"oneCollectionField"`
	OneAllowedCollections null_v4.String `db:"one_allowed_collections" json:"oneAllowedCollections"`
	JunctionField         null_v4.String `db:"junction_field" json:"junctionField"`
	SortField             null_v4.String `db:"sort_field" json:"sortField"`
	OneDeselectAction     string         `db:"one_deselect_action" json:"oneDeselectAction"`
}

type DirectusRevisions struct {
	ID         int32                 `db:"id" json:"id"`
	Activity   int32                 `db:"activity" json:"activity"`
	Collection string                `db:"collection" json:"collection"`
	Item       string                `db:"item" json:"item"`
	Data       pqtype.NullRawMessage `db:"data" json:"data"`
	Delta      pqtype.NullRawMessage `db:"delta" json:"delta"`
	Parent     null_v4.Int           `db:"parent" json:"parent"`
}

type DirectusRoles struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Icon        string         `db:"icon" json:"icon"`
	Description null_v4.String `db:"description" json:"description"`
	IpAccess    null_v4.String `db:"ip_access" json:"ipAccess"`
	EnforceTfa  bool           `db:"enforce_tfa" json:"enforceTfa"`
	AdminAccess bool           `db:"admin_access" json:"adminAccess"`
	AppAccess   bool           `db:"app_access" json:"appAccess"`
}

type DirectusSessions struct {
	Token     string         `db:"token" json:"token"`
	User      uuid.NullUUID  `db:"user" json:"user"`
	Expires   time.Time      `db:"expires" json:"expires"`
	Ip        null_v4.String `db:"ip" json:"ip"`
	UserAgent null_v4.String `db:"user_agent" json:"userAgent"`
	Share     uuid.NullUUID  `db:"share" json:"share"`
}

type DirectusSettings struct {
	ID                    int32                 `db:"id" json:"id"`
	ProjectName           string                `db:"project_name" json:"projectName"`
	ProjectUrl            null_v4.String        `db:"project_url" json:"projectUrl"`
	ProjectColor          null_v4.String        `db:"project_color" json:"projectColor"`
	ProjectLogo           uuid.NullUUID         `db:"project_logo" json:"projectLogo"`
	PublicForeground      uuid.NullUUID         `db:"public_foreground" json:"publicForeground"`
	PublicBackground      uuid.NullUUID         `db:"public_background" json:"publicBackground"`
	PublicNote            null_v4.String        `db:"public_note" json:"publicNote"`
	AuthLoginAttempts     null_v4.Int           `db:"auth_login_attempts" json:"authLoginAttempts"`
	AuthPasswordPolicy    null_v4.String        `db:"auth_password_policy" json:"authPasswordPolicy"`
	StorageAssetTransform null_v4.String        `db:"storage_asset_transform" json:"storageAssetTransform"`
	StorageAssetPresets   pqtype.NullRawMessage `db:"storage_asset_presets" json:"storageAssetPresets"`
	CustomCss             null_v4.String        `db:"custom_css" json:"customCss"`
	StorageDefaultFolder  uuid.NullUUID         `db:"storage_default_folder" json:"storageDefaultFolder"`
	Basemaps              pqtype.NullRawMessage `db:"basemaps" json:"basemaps"`
	MapboxKey             null_v4.String        `db:"mapbox_key" json:"mapboxKey"`
	ModuleBar             pqtype.NullRawMessage `db:"module_bar" json:"moduleBar"`
	ProjectDescriptor     null_v4.String        `db:"project_descriptor" json:"projectDescriptor"`
	TranslationStrings    pqtype.NullRawMessage `db:"translation_strings" json:"translationStrings"`
	DefaultLanguage       string                `db:"default_language" json:"defaultLanguage"`
}

type DirectusShares struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        null_v4.String `db:"name" json:"name"`
	Collection  null_v4.String `db:"collection" json:"collection"`
	Item        null_v4.String `db:"item" json:"item"`
	Role        uuid.NullUUID  `db:"role" json:"role"`
	Password    null_v4.String `db:"password" json:"password"`
	UserCreated uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	DateStart   sql.NullTime   `db:"date_start" json:"dateStart"`
	DateEnd     sql.NullTime   `db:"date_end" json:"dateEnd"`
	TimesUsed   null_v4.Int    `db:"times_used" json:"timesUsed"`
	MaxUses     null_v4.Int    `db:"max_uses" json:"maxUses"`
}

type DirectusUsers struct {
	ID                 uuid.UUID             `db:"id" json:"id"`
	FirstName          null_v4.String        `db:"first_name" json:"firstName"`
	LastName           null_v4.String        `db:"last_name" json:"lastName"`
	Email              null_v4.String        `db:"email" json:"email"`
	Password           null_v4.String        `db:"password" json:"password"`
	Location           null_v4.String        `db:"location" json:"location"`
	Title              null_v4.String        `db:"title" json:"title"`
	Description        null_v4.String        `db:"description" json:"description"`
	Tags               pqtype.NullRawMessage `db:"tags" json:"tags"`
	Avatar             uuid.NullUUID         `db:"avatar" json:"avatar"`
	Language           null_v4.String        `db:"language" json:"language"`
	Theme              null_v4.String        `db:"theme" json:"theme"`
	TfaSecret          null_v4.String        `db:"tfa_secret" json:"tfaSecret"`
	Status             string                `db:"status" json:"status"`
	Role               uuid.NullUUID         `db:"role" json:"role"`
	Token              null_v4.String        `db:"token" json:"token"`
	LastAccess         sql.NullTime          `db:"last_access" json:"lastAccess"`
	LastPage           null_v4.String        `db:"last_page" json:"lastPage"`
	Provider           string                `db:"provider" json:"provider"`
	ExternalIdentifier null_v4.String        `db:"external_identifier" json:"externalIdentifier"`
	AuthData           pqtype.NullRawMessage `db:"auth_data" json:"authData"`
	EmailNotifications sql.NullBool          `db:"email_notifications" json:"emailNotifications"`
}

type DirectusWebhooks struct {
	ID          int32                 `db:"id" json:"id"`
	Name        string                `db:"name" json:"name"`
	Method      string                `db:"method" json:"method"`
	Url         string                `db:"url" json:"url"`
	Status      string                `db:"status" json:"status"`
	Data        bool                  `db:"data" json:"data"`
	Actions     string                `db:"actions" json:"actions"`
	Collections string                `db:"collections" json:"collections"`
	Headers     pqtype.NullRawMessage `db:"headers" json:"headers"`
}

type Episodes struct {
	ID            int32                 `db:"id" json:"id"`
	Status        string                `db:"status" json:"status"`
	UserCreated   uuid.NullUUID         `db:"user_created" json:"userCreated"`
	DateCreated   sql.NullTime          `db:"date_created" json:"dateCreated"`
	UserUpdated   uuid.NullUUID         `db:"user_updated" json:"userUpdated"`
	DateUpdated   sql.NullTime          `db:"date_updated" json:"dateUpdated"`
	AvailableFrom null_v4.Time          `db:"available_from" json:"availableFrom"`
	AvailableTo   null_v4.Time          `db:"available_to" json:"availableTo"`
	AgeratingCode null_v4.String        `db:"agerating_code" json:"ageratingCode"`
	SeasonID      null_v4.Int           `db:"season_id" json:"seasonID"`
	MigrationData pqtype.NullRawMessage `db:"migration_data" json:"migrationData"`
	PublishDate   time.Time             `db:"publish_date" json:"publishDate"`
	Type          string                `db:"type" json:"type"`
	ImageFileID   uuid.NullUUID         `db:"image_file_id" json:"imageFileID"`
}

type EpisodesTranslations struct {
	ID          int32          `db:"id" json:"id"`
	EpisodesID  null_v4.Int    `db:"episodes_id" json:"episodesID"`
	LanguagesID null_v4.String `db:"languages_id" json:"languagesID"`
	Title       null_v4.String `db:"title" json:"title"`
	Description null_v4.String `db:"description" json:"description"`
	IsPrimary   sql.NullBool   `db:"is_primary" json:"isPrimary"`
}

type EpisodesUsergroups struct {
	ID             int32          `db:"id" json:"id"`
	EpisodesID     null_v4.Int    `db:"episodes_id" json:"episodesID"`
	UsergroupsCode null_v4.String `db:"usergroups_code" json:"usergroupsCode"`
}

type Featureds struct {
	ID          int32         `db:"id" json:"id"`
	Status      string        `db:"status" json:"status"`
	Sort        null_v4.Int   `db:"sort" json:"sort"`
	UserCreated uuid.NullUUID `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime  `db:"date_created" json:"dateCreated"`
	UserUpdated uuid.NullUUID `db:"user_updated" json:"userUpdated"`
	DateUpdated sql.NullTime  `db:"date_updated" json:"dateUpdated"`
}

type Languages struct {
	Code              string         `db:"code" json:"code"`
	Name              null_v4.String `db:"name" json:"name"`
	Legacy3LetterCode null_v4.String `db:"legacy_3_letter_code" json:"legacy3LetterCode"`
	Legacy2LetterCode null_v4.String `db:"legacy_2_letter_code" json:"legacy2LetterCode"`
}

type Pages struct {
	ID          int32          `db:"id" json:"id"`
	Status      string         `db:"status" json:"status"`
	Sort        null_v4.Int    `db:"sort" json:"sort"`
	UserCreated uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Code        null_v4.String `db:"code" json:"code"`
}

type Seasons struct {
	ID            int32          `db:"id" json:"id"`
	Status        string         `db:"status" json:"status"`
	UserCreated   uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated   sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated   uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated   sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	AvailableFrom null_v4.Time   `db:"available_from" json:"availableFrom"`
	AvailableTo   null_v4.Time   `db:"available_to" json:"availableTo"`
	ShowID        int32          `db:"show_id" json:"showID"`
	AgeratingCode null_v4.String `db:"agerating_code" json:"ageratingCode"`
	PublishDate   time.Time      `db:"publish_date" json:"publishDate"`
	ImageFileID   uuid.NullUUID  `db:"image_file_id" json:"imageFileID"`
}

type SeasonsTranslations struct {
	ID            int32          `db:"id" json:"id"`
	SeasonsID     null_v4.Int    `db:"seasons_id" json:"seasonsID"`
	LanguagesCode null_v4.String `db:"languages_code" json:"languagesCode"`
	Title         null_v4.String `db:"title" json:"title"`
	Description   null_v4.String `db:"description" json:"description"`
	LegacyTags    null_v4.String `db:"legacy_tags" json:"legacyTags"`
}

type SeasonsUsergroups struct {
	ID             int32          `db:"id" json:"id"`
	SeasonsID      null_v4.Int    `db:"seasons_id" json:"seasonsID"`
	UsergroupsCode null_v4.String `db:"usergroups_code" json:"usergroupsCode"`
}

type Sections struct {
	ID          int32         `db:"id" json:"id"`
	Status      string        `db:"status" json:"status"`
	UserCreated uuid.NullUUID `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime  `db:"date_created" json:"dateCreated"`
	UserUpdated uuid.NullUUID `db:"user_updated" json:"userUpdated"`
	DateUpdated sql.NullTime  `db:"date_updated" json:"dateUpdated"`
	Page        null_v4.Int   `db:"page" json:"page"`
	Title       string        `db:"title" json:"title"`
}

type SectionsUsergroups struct {
	ID             int32          `db:"id" json:"id"`
	SectionsID     null_v4.Int    `db:"sections_id" json:"sectionsID"`
	UsergroupsCode null_v4.String `db:"usergroups_code" json:"usergroupsCode"`
}

type Shows struct {
	ID            int32                 `db:"id" json:"id"`
	Status        string                `db:"status" json:"status"`
	UserCreated   uuid.NullUUID         `db:"user_created" json:"userCreated"`
	DateCreated   sql.NullTime          `db:"date_created" json:"dateCreated"`
	UserUpdated   uuid.NullUUID         `db:"user_updated" json:"userUpdated"`
	DateUpdated   sql.NullTime          `db:"date_updated" json:"dateUpdated"`
	Title         string                `db:"title" json:"title"`
	Description   null_v4.String        `db:"description" json:"description"`
	Image         uuid.NullUUID         `db:"image" json:"image"`
	AvailableFrom null_v4.Time          `db:"available_from" json:"availableFrom"`
	AvailableTo   null_v4.Time          `db:"available_to" json:"availableTo"`
	MigrationData pqtype.NullRawMessage `db:"migration_data" json:"migrationData"`
	PublishDate   time.Time             `db:"publish_date" json:"publishDate"`
	Type          string                `db:"type" json:"type"`
	AgeratingCode null_v4.String        `db:"agerating_code" json:"ageratingCode"`
	ImageFileID   uuid.NullUUID         `db:"image_file_id" json:"imageFileID"`
}

type ShowsUsergroups struct {
	ID             int32          `db:"id" json:"id"`
	ShowsID        null_v4.Int    `db:"shows_id" json:"showsID"`
	UsergroupsCode null_v4.String `db:"usergroups_code" json:"usergroupsCode"`
}

type Tvguideentry struct {
	ID               int32          `db:"id" json:"id"`
	Status           null_v4.String `db:"status" json:"status"`
	UserCreated      uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated      sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated      uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated      sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Title            null_v4.String `db:"title" json:"title"`
	Description      null_v4.String `db:"description" json:"description"`
	Image            uuid.NullUUID  `db:"image" json:"image"`
	Event            null_v4.Int    `db:"event" json:"event"`
	Start            null_v4.Time   `db:"start" json:"start"`
	End              null_v4.Time   `db:"end" json:"end"`
	UseImageFromLink bool           `db:"use_image_from_link" json:"useImageFromLink"`
}

type TvguideentryLink struct {
	ID             int32          `db:"id" json:"id"`
	TvguideentryID null_v4.Int    `db:"tvguideentry_id" json:"tvguideentryID"`
	Item           null_v4.String `db:"item" json:"item"`
	Collection     null_v4.String `db:"collection" json:"collection"`
}

type Usergroups struct {
	Code        string         `db:"code" json:"code"`
	Sort        null_v4.Int    `db:"sort" json:"sort"`
	UserCreated uuid.NullUUID  `db:"user_created" json:"userCreated"`
	DateCreated sql.NullTime   `db:"date_created" json:"dateCreated"`
	UserUpdated uuid.NullUUID  `db:"user_updated" json:"userUpdated"`
	DateUpdated sql.NullTime   `db:"date_updated" json:"dateUpdated"`
	Name        null_v4.String `db:"name" json:"name"`
}
