// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: pages.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const getPages = `-- name: GetPages :many
SELECT id, code, type, published, show_id, season_id, episode_id, collection, title, description, roles FROM pages_expanded WHERE id = ANY ($1::int[])
`

func (q *Queries) GetPages(ctx context.Context, dollar_1 []int32) ([]PagesExpanded, error) {
	rows, err := q.db.QueryContext(ctx, getPages, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PagesExpanded
	for rows.Next() {
		var i PagesExpanded
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Published,
			&i.ShowID,
			&i.SeasonID,
			&i.EpisodeID,
			&i.Collection,
			&i.Title,
			&i.Description,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPages = `-- name: ListPages :many
SELECT id, code, type, published, show_id, season_id, episode_id, collection, title, description, roles FROM pages_expanded
`

func (q *Queries) ListPages(ctx context.Context) ([]PagesExpanded, error) {
	rows, err := q.db.QueryContext(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PagesExpanded
	for rows.Next() {
		var i PagesExpanded
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Published,
			&i.ShowID,
			&i.SeasonID,
			&i.EpisodeID,
			&i.Collection,
			&i.Title,
			&i.Description,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
