// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqladminmodel

type CollectionItem struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type Preview struct {
	Collection *PreviewCollection `json:"collection"`
}

type PreviewCollection struct {
	Items []*CollectionItem `json:"items"`
}
