install:
	cd ./interface-query-builder && pnpm i
	cd ./interface-video-viewer && pnpm i
	cd ./interface-datepicker && pnpm i

build:
	cd ./interface-query-builder && pnpm build
	cd ./interface-video-viewer && pnpm build
	cd ./interface-datepicker && pnpm build

init:
	cd ./interface-query-builder && pnpm i
	cd ./interface-video-viewer && pnpm i
	cd ./interface-datepicker && pnpm i
	make build
