install:
	cd ./interface-query-builder && npm ci
	cd ./interface-video-viewer && npm ci
	cd ./interface-datepicker && npm ci

build:
	cd ./interface-query-builder && npm run build
	cd ./interface-video-viewer && npm run build
	cd ./interface-datepicker && npm run build

init:
	cd ./interface-query-builder && npm i
	cd ./interface-video-viewer && npm i
	cd ./interface-datepicker && npm i
	make build