"project_id": "525828"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"api_token_env": "CROWDIN_TOKEN"

files:
    [
        {
            "source": "/localized/nb.json",
            "translation": "/localized/%two_letters_code%.json",
            "dest": "/manual/quotes.json",
            "export_only_approved": true,
            "skip_untranslated_strings": false,
        },
    ]
