// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlexport

import (
	"database/sql"
)

type Application struct {
	ID            int64         `db:"id" json:"id"`
	Code          string        `db:"code" json:"code"`
	ClientVersion string        `db:"client_version" json:"clientVersion"`
	DefaultPageID sql.NullInt64 `db:"default_page_id" json:"defaultPageId"`
}

type Collection struct {
	ID              int64  `db:"id" json:"id"`
	Name            string `db:"name" json:"name"`
	CollectionItems string `db:"collection_items" json:"collectionItems"`
}

type Episode struct {
	ID               int64          `db:"id" json:"id"`
	LegacyID         sql.NullInt64  `db:"legacy_id" json:"legacyId"`
	LegacyProgramID  sql.NullInt64  `db:"legacy_program_id" json:"legacyProgramId"`
	AgeRating        string         `db:"age_rating" json:"ageRating"`
	Title            string         `db:"title" json:"title"`
	Description      string         `db:"description" json:"description"`
	ExtraDescription string         `db:"extra_description" json:"extraDescription"`
	Images           string         `db:"images" json:"images"`
	ProductionDate   sql.NullString `db:"production_date" json:"productionDate"`
	SeasonID         sql.NullInt64  `db:"season_id" json:"seasonId"`
	Duration         int64          `db:"duration" json:"duration"`
	Number           int64          `db:"number" json:"number"`
}

type Page struct {
	ID          int64  `db:"id" json:"id"`
	Code        string `db:"code" json:"code"`
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Images      string `db:"images" json:"images"`
	SectionIds  string `db:"section_ids" json:"sectionIds"`
}

type Season struct {
	ID          int64         `db:"id" json:"id"`
	LegacyID    sql.NullInt64 `db:"legacy_id" json:"legacyId"`
	TagIds      string        `db:"tag_ids" json:"tagIds"`
	Number      int64         `db:"number" json:"number"`
	AgeRating   string        `db:"age_rating" json:"ageRating"`
	Title       string        `db:"title" json:"title"`
	Description string        `db:"description" json:"description"`
	ShowID      int64         `db:"show_id" json:"showId"`
	Images      string        `db:"images" json:"images"`
}

type Section struct {
	ID           int64         `db:"id" json:"id"`
	Sort         int64         `db:"sort" json:"sort"`
	PageID       int64         `db:"page_id" json:"pageId"`
	Type         string        `db:"type" json:"type"`
	ShowTitle    bool          `db:"show_title" json:"showTitle"`
	Title        string        `db:"title" json:"title"`
	Description  string        `db:"description" json:"description"`
	Style        string        `db:"style" json:"style"`
	Size         string        `db:"size" json:"size"`
	CollectionID sql.NullInt64 `db:"collection_id" json:"collectionId"`
}

type Show struct {
	ID             int64         `db:"id" json:"id"`
	Type           string        `db:"type" json:"type"`
	LegacyID       sql.NullInt64 `db:"legacy_id" json:"legacyId"`
	Title          string        `db:"title" json:"title"`
	Description    string        `db:"description" json:"description"`
	Images         string        `db:"images" json:"images"`
	DefaultEpisode sql.NullInt64 `db:"default_episode" json:"defaultEpisode"`
}

type Stream struct {
	ID                int64          `db:"id" json:"id"`
	EpisodeID         int64          `db:"episode_id" json:"episodeId"`
	Url               string         `db:"url" json:"url"`
	AudioLanguages    string         `db:"audio_languages" json:"audioLanguages"`
	SubtitleLanguages string         `db:"subtitle_languages" json:"subtitleLanguages"`
	Type              string         `db:"type" json:"type"`
	VideoLanguage     sql.NullString `db:"video_language" json:"videoLanguage"`
}
