package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/bcc-code/bcc-media-platform/backend/common"
	"github.com/bcc-code/bcc-media-platform/backend/graph/api/generated"
	"github.com/bcc-code/bcc-media-platform/backend/graph/api/model"
	"github.com/bcc-code/bcc-media-platform/backend/utils"
	"github.com/google/uuid"
)

// Key is the resolver for the key field.
func (r *songResolver) Key(ctx context.Context, obj *model.Song) (string, error) {
	song, err := r.Loaders.SongLoader.Get(ctx, utils.AsUuid(obj.ID))
	if err != nil || song == nil {
		return "", err
	}
	col, err := r.Loaders.SongCollectionLoader.Get(ctx, song.CollectionID)
	if err != nil || col == nil || col.Code == "" {
		return song.Key, err
	}
	return col.Code + "-" + song.Key, nil
}

// Collection is the resolver for the collection field.
func (r *songResolver) Collection(ctx context.Context, obj *model.Song) (*model.SongCollection, error) {
	song, err := r.Loaders.SongLoader.Get(ctx, utils.AsUuid(obj.ID))
	if err != nil || song == nil {
		return nil, err
	}
	col, err := r.Loaders.SongCollectionLoader.Get(ctx, song.CollectionID)
	if err != nil || col == nil {
		return nil, err
	}
	return model.SongCollectionFrom(col), nil
}

// Contributors is the resolver for the contributors field.
func (r *songResolver) Contributors(ctx context.Context, obj *model.Song) ([]*model.Contributor, error) {
	songID := utils.AsUuid(obj.ID)

	rows, err := r.Loaders.SongContributionsLoader.Get(ctx, songID)
	if err != nil {
		return nil, err
	}

	type personContributions struct {
		personID uuid.UUID
		types    map[string]bool
	}
	contributorMap := make(map[uuid.UUID]*personContributions)

	for _, c := range rows {
		if c == nil {
			continue
		}
		if contributorMap[c.PersonID] == nil {
			contributorMap[c.PersonID] = &personContributions{
				personID: c.PersonID,
				types:    make(map[string]bool),
			}
		}
		contributorMap[c.PersonID].types[c.Type] = true
	}

	if len(contributorMap) == 0 {
		return nil, nil
	}

	personIDs := make([]uuid.UUID, 0, len(contributorMap))
	for id := range contributorMap {
		personIDs = append(personIDs, id)
	}

	persons, err := r.Loaders.PersonLoader.GetMany(ctx, personIDs)
	if err != nil {
		return nil, err
	}

	personMap := make(map[uuid.UUID]*common.Person, len(persons))
	for i, p := range persons {
		if p != nil {
			personMap[personIDs[i]] = p
		}
	}

	var contributors []*model.Contributor
	for _, pc := range contributorMap {
		person, ok := personMap[pc.personID]
		if !ok || person == nil {
			continue
		}

		var contributionTypes []model.ContributionTypeCode
		for t := range pc.types {
			contributionTypes = append(contributionTypes, stringToContributionTypeCode(t))
		}

		contributors = append(contributors, &model.Contributor{
			Person:            model.PersonFrom(ctx, person),
			ContributionTypes: contributionTypes,
		})
	}

	return contributors, nil
}

// Song returns generated.SongResolver implementation.
func (r *Resolver) Song() generated.SongResolver { return &songResolver{r} }

type songResolver struct{ *Resolver }
