#schema: "https://api.brunstad.tv/query"
schema: '../backend/graph/api/schema/*.graphqls'
documents: 'src/**/*.{graphql,js,ts,jsx,tsx}'
extensions:
    languageService:
        cacheSchemaFileForLookup: true
